[build-system]
requires = ["setuptools >= 82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "meshpages"
version = "0.0.1"
authors = [
  { name="Devon Slonaker", email="mushroomgecko@gmail.com" },
]
description = "An application and web framework for serving and recieving HTML pages over the Meshtastic network"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
dependencies = [
    "meshtastic>=2.7.8",
    "fastapi>=0.136.1",
    "uvicorn",
    "jinja2",
    "python-multipart",
    "brotli>=1.2.0",
]

[project.optional-dependencies]
default = [
    "minify-html-onepass>=0.18.1",
]
termux = [
    "htmlmin4>=0.2.15",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.uv]
conflicts = [
    [
        { extra = "default" },
        { extra = "termux" },
    ],
]

[[tool.uv.index]]
name = "termux"
url = "https://termux-user-repository.github.io/pypi/"
explicit = true

[tool.uv.sources]
pydantic-core = [{ index = "termux", extra = "termux" }]

[tool.black]
line-length = 9999
target-version = ["py312"]
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 9999